"use client";

import { useEffect, useState } from "react";
import QRCode from "qrcode";

type Props = {
  value: string;
  size?: number;
  className?: string;
  margin?: number;
};

/**
 * Renders a QR code as inline SVG. Re-renders when `value` changes.
 * Uses qrcode.toString with type 'svg' so it scales perfectly on any size.
 */
export function QrCode({ value, size = 220, className, margin = 1 }: Props) {
  const [svg, setSvg] = useState<string>("");

  useEffect(() => {
    let cancelled = false;
    QRCode.toString(value, {
      type: "svg",
      margin,
      errorCorrectionLevel: "M",
      color: {
        dark: "#1f1208",
        light: "#ffffff",
      },
    })
      .then((str) => {
        if (!cancelled) setSvg(str);
      })
      .catch(() => {
        if (!cancelled) setSvg("");
      });
    return () => {
      cancelled = true;
    };
  }, [value, margin]);

  return (
    <div
      className={className}
      style={{ width: size, height: size }}
      // svg output is generated by qrcode lib, safe to inject
      dangerouslySetInnerHTML={{ __html: svg }}
      aria-label={`QR code for ${value}`}
      role="img"
    />
  );
}
